
context:
  name: pytblis
  version: 0.0.13

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  git: https://github.com/chillenb/pytblis.git
  tag: "v${{ version }}"

build:
  script:
    content: |
      export CMAKE_BUILD_PARALLEL_LEVEL=${CPU_COUNT}
      export SKBUILD_CMAKE_ARGS=${CMAKE_ARGS}
      $PYTHON -m pip install --no-build-isolation --no-deps . -vv
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake >=3.10
    - make
    - setuptools
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
  host:
    - python
    - setuptools
    - setuptools_scm
    - pip
    - nanobind
    - nanobind-abi
    - scikit-build-core
    - tblis-dev >1
  run:
    - python
    - numpy

tests:
  - script:
    - pytest tests -v
    requirements:
      run:
        - pytest
        - pytest-cov
    files:
      source:
        - tests/
  - python:
      imports:
        - pytblis

about:
  homepage: https://github.com/chillenb/pytblis
  summary: Python bindings for TBLIS
  license: BSD-3-Clause
  license_file: LICENSE
  repository: https://github.com/chillenb/pytblis

extra:
  recipe-maintainers:
    - chillenb
