name: Build libcint

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linux-64
            packagedir: libcint
          - os: macos-latest
            target: osx-arm64
            packagedir: libcint
          - os: windows-latest
            target: win-64
            packagedir: libcint
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: prefix-dev/setup-pixi@v0.8.8
        with:
          pixi-version: v0.47.0
          cache: true
          locked: false

      - name: Build libcint package
        shell: bash
        env:
          TARGET_PLATFORM: ${{ matrix.target }}
          PACKAGEDIR: ${{ matrix.packagedir }}
          ANACONDA_API_KEY: ${{ secrets.ANACONDA_API_KEY }}

        run: |
          pixi run rattler-build build --recipe-dir $PACKAGEDIR \
            --skip-existing=all --target-platform=$TARGET_PLATFORM \
            -c restgroup -c conda-forge

          # ignore errors because we want to ignore duplicate packages
          for file in output/**/*.conda; do
            pixi run rattler-build upload anaconda -o restgroup "$file" || true
          done
